[package]
name = "glorp"
version = "0.2.0"
edition = "2024"

[dependencies]
askama = "0.15"
axum = "0.8"
tokio = { version = "1.53.1", features = ["full"] }

displaydoc = "0.2.7"
thiserror = "2.0.21"
tower = { version = "0.5.3", features = ["full"] }
tower-http = { version = "0.6.11", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
rand = "0.10.3"
clap = { version = "4.6.7", features = ["derive"] }
